config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
    namespace :admin do
     root 'admin#index'
     resources :users, only: [:index, :create, :destroy]
     resources :posts, only: [:index, :destroy]
     resources :comments, only: [:index, :destroy]
     resources :tags, only: [:index, :destroy]
    end
  resources :users do
    resources :bookmarks, only: [:create, :destroy, :index]
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  get 'search', to: "static_pages#search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  default_scope -> { order(created_at: :desc) }
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController

 def index
  @comment = Comment.all.paginate(page: params[:page])
 end

 def destroy
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to admin_comments_path
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.user == current_user
      @comment.destroy
      redirect_to post_path(@post)
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/admin/comments/_comment.html.erb
<tr>
  <td><%= comment.id %></td>
  <td><%= link_to comment.user.name, user_path(comment.user) %></td>
  <td><%= link_to comment.post.title, post_path(comment.post) %></td>
  <td><%= comment.content %></td>
  <td><%= comment.created_at %></td>
  <!-- <td>
    <%#= comment.admin == true ? "Admin" : "Member" %>
  </td> -->
  <td>
    <%= link_to "Delete", admin_comment_path(comment), method: :delete %>
  </td>
</tr>

app/views/admin/comments/index.html.erb
<div class="container-fluid">
 <div class="row">
  <%= render "admin/admin/sidebar" %>
  <h2 class="sub-header">Comment List</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Comment by</th>
                  <th>Post</th>
                  <th>Content</th>
                  <th>Create At</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "comment", collection: @comment %>
              </tbody>
            </table>
            <%= will_paginate @comment %>
          </div>
 </div>
</div>