config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
    namespace :admin do
     root 'admin#index'
     resources :users, only: [:index, :create, :destroy]
     resources :posts, only: [:index, :destroy]
     resources :comments, only: [:index, :destroy]
     resources :tags, only: [:index, :destroy]
    end
  resources :users do
    resources :bookmarks, only: [:create, :destroy, :index]
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  get 'search', to: "static_pages#search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy
    has_many :posts, through: :taggings
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController

 def index
  @tag = Tag.all.paginate(page: params[:page])
 end

 def destroy
  @tag = Tag.find(params[:id])
  @tag.destroy
  redirect_to admin_tags_path
 end
end

app/views/admin/tags/_tag.html.erb
<tr>
  <td><%= tag.id %></td>
  <!-- <td><%#= tag.posts %></td> -->
  <td><%= tag.name %></td>
  <td><%= tag.created_at %></td>
  <td>
    <%= link_to "Delete", admin_tag_path(tag), method: :delete %>
  </td>
</tr>

app/views/admin/tags/index.html.erb
<div class="container-fluid">
 <div class="row">
  <%= render "admin/admin/sidebar" %>
  <h2 class="sub-header">Tag List</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Tag Name</th>
                 <!--  <th>Post</th>
                  <th>Content</th> -->
                  <th>Create At</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
                <%= render partial: "tag", collection: @tag %>
              </tbody>
            </table>
            <%= will_paginate @tag %>
          </div>
 </div>
</div>