config/routes.rb
Rails.application.routes.draw do

  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
    namespace :admin do
     root 'admin#index'
     resources :users, only: [:index, :create, :destroy]
     resources :posts, only: [:index, :destroy]
     resources :comments, only: [:index, :destroy]
     resources :tags, only: [:index, :destroy]
    end
  resources :users do
    resources :bookmarks, only: [:create, :destroy, :index]
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :dislikes, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  get 'search', to: "static_pages#search"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/admin/_sidebar.html.erb
 <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active">
              <%= link_to admin_root_path do%>
                Overview <span class="sr-only">(current)</span>
              <% end %>
            </li>
             <!--  <a href="#">Overview <span class="sr-only">(current)</span></a></li> -->
            <li><%= link_to "Users", admin_users_path %></li>
            <li><%= link_to "Posts", admin_posts_path %></li>
            <li><%= link_to "Comments", admin_comments_path %></li>
            <li><%= link_to "Tags", admin_tags_path %></li>
          </ul>
          <!-- <ul class="nav nav-sidebar">
            <li><a href="">Images</a></li>
            <li><a href="">Bookmarks</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul> -->
          <!-- <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul> -->
 </div>

app/views/admin/admin/index.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render "sidebar" %>
    <div class="col-sm-9 col-md-10 main">
      <h1 class="page-header">Dashboard</h1>
        <div class="row placeholders">
          <div class="col-xs-6 col-sm-3 placeholder ">
            <%= link_to admin_users_path, class: "btn btn btn-lg" do %>
             <span class="glyphicon glyphicon-log-in"></span>
             <%= @user.count %>
            <% end %>
            <h4>Total Users</h4>
          </div>
          <div class="col-xs-6 col-sm-3 placeholder">
            <%= link_to admin_users_path, class: "btn btn btn-lg" do %>
             <span class="glyphicon glyphicon-log-in"></span>
             <%= @post.count %>
            <% end %>
            <h4>Total Posts</h4>
          </div>
          <div class="col-xs-6 col-sm-3 placeholder">
            <%= link_to admin_comments_path, class: "btn btn btn-lg" do %>
             <span class="glyphicon glyphicon-log-in"></span>
             <%= @comment.count %>
            <% end %>
            <h4>Total Comments</h4>
          </div>
          <div class="col-xs-6 col-sm-3 placeholder">
            <%= link_to admin_tags_path, class: "btn btn btn-lg" do %>
             <span class="glyphicon glyphicon-log-in"></span>
             <%= @tag.count %>
            <% end %>
            <h4>Totals Tags</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>